In [ ]:
import pandas as pd
data = pd.read_csv( 'titanic.csv' , index_col='PassengerId')
data

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

1. Какое количество мужчин и женщин ехало на корабле? В качестве ответа приведите два числа через пробел

In [ ]:
count_sex=data['Sex'].value_counts().to_list()
print(count_sex[0],count_sex[1])

577 314

2. Какой части пассажиров удалось выжить? Посчитайте долю выживших пассажиров. Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.

In [ ]:
round((data['Survived'].sum()/data.shape[0])*100,2)

38.38

 3. Какую долю пассажиры первого класса составляли среди всех пассажиров? Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.

In [ ]:
round((data[data['Pclass']==1].shape[0]/data.shape[0])*100,2)

24.24

 4. Какого возраста были пассажиры? Посчитайте среднее и медиану возраста пассажиров. Посчитайте среднее и медиану возраста пассажиров. В качестве ответа приведите два числа через пробел.

In [ ]:
average_mediana=data['Age'].describe().iloc[1:6:4].to_list()# можно и через mean и median
print(round(average_mediana[0],2),average_mediana[1])

29.7 28.0

 5. Коррелируют ли число братьев/сестер с числом родителей/детей?
 Посчитайте корреляцию Пирсона между признаками SibSp и Parch.

In [ ]:
matrix_corr=data[['Parch','SibSp']].corr()
matrix_corr

          Parch     SibSp
Parch  1.000000  0.414838
SibSp  0.414838  1.000000

6. Какое самое популярное женское имя на корабле? Извлеките из полного имени пассажира (колонка Name) его личное имя (First Name). Это задание типичный пример того, с чем сталкивается специалист по анализу данных. Данные очень разнородные и шумные, но из них требуется извлечь необходимую информацию.
 Попробуйте вручную разобрать несколько значений столбца Name и выработать правило для извлечения имен, а также разделения
 их на женские и мужские.

In [ ]:
woman=data[data['Sex']=='female']
woman['Name'].str.split(',').str[1].str.split('.').str[0].unique()

array([' Mrs', ' Miss', ' Mme', ' Ms', ' Lady', ' Mlle', ' the Countess',
       ' Dr'], dtype=object)

In [ ]:
import re
def name_female(name):
    match = re.search("^[^,]+, (.*)", name)#после запятой
    if match:
        name = match[1]

    match = re.search("\(([^)]+)\)", name) #в скобках
    if match:
        name = match[1]
    name = re.sub("(Miss\. |Mrs\. |Ms\. |Mlle\. |Mme\. |Lady\. |Dr\. |the Countess\. )", "", name)#исключаем статусы


    name = name.split(" ")[0].replace('"','')#первое как раз нужное нам имя

    return name

In [ ]:
names = data[data["Sex"] == "female"]["Name"].map(name_female)
names.value_counts()

Name
Mary           15
Anna           15
Elizabeth      11
Margaret       10
Alice           6
Helen           5
Bertha          5
Marie           4
Ada             4
Maria           4
Marion          4
Emily           4
Annie           4
Catherine       4
Augusta         4
Florence        4
Ellen           4
Ida             3
Katherine       3
Mrs             3
Edith           3
Jane            3
Madeleine       3
Amelia          3
Hanora          3
Lillian         3
Elisabeth       3
Martha          2
Rosa            2
Amy             2
Marjorie        2
Kate            2
Helene          2
Charlotte       2
Lucile          2
Agnes           2
Emma            2
Elsie           2
Ethel           2
Lucy            2
Hedwig          2
Jessie          2
Marija          2
Rosalie         2
Clara           2
Bridget         2
Lily            2
Dorothy         2
Johanna         2
Constance       2
Adele           2
Susan           2
Mabel           2
Mathilde        2
Alfrida         1
Juliette        1
Hulda           1
Cordelia        1
Gretchen        1
Margit          1
Ruth            1
Marian          1
Julie           1
Marguerite      1
Alma            1
Elin            1
Tillie          1
Juliet          1
Lucille         1
Velin           1
Emelia          1
Sigrid          1
Ingeborg        1
Harriet         1
Eva             1
Phyllis         1
Fatima          1
Anne            1
Roberta         1
Kristina        1
Eugenie         1
Georgette       1
Katie           1
Torborg         1
Imanita         1
Hannah          1
Sallie          1
Asuncion        1
Karolina        1
Latifa          1
Leah            1
Lilian          1
Nourelain       1
Edwiga          1
Sara            1
Selini          1
Beila           1
Wendla          1
Ebba            1
Mara            1
Farnham         1
Stella          1
Vera            1
Banoura         1
Virginia        1
Eliza           1
Joan            1
Pieta           1
Margareth       1
Edwina          1
Caroline        1
Saiide          1
Manca           1
Bessie          1
Encarnacion     1
Jeannie         1
Katriina        1
Aloisia         1
Kornelia        1
Matilda         1
Hileni          1
Delia           1
Lutie           1
Gladys          1
Gertrude        1
Hanne           1
Helena          1
Elna            1
Agda            1
Thamine         1
Malake          1
Selma           1
Irene           1
Albina          1
Eliina          1
Ellis           1
Clear           1
Telma           1
Elise           1
Carla           1
Grace           1
Luise           1
Ann             1
Eleanor         1
Sultana         1
Brigdet         1
Nora            1
Laura           1
Helmina         1
Hildur          1
Robina          1
Esther          1
Doolina         1
Jamila          1
Catharina       1
Lyyli           1
Lulu            1
Daisy           1
Mari            1
Simonne         1
Elina           1
Aurora          1
Leila           1
Stina           1
Leontine        1
Mantoura        1
Josefine        1
Myna            1
Amelie          1
Laina           1
Erna            1
Jean            1
Sylvia          1
Hilda           1
Margaretta      1
Miriam          1
Gerda           1
Name: count, dtype: int64