 1. Загрузите данные close_prices.csv. В этом файле приведены цены
 акций 30 компаний на закрытии торгов за каждый день периода.

In [ ]:
import pandas as pd

df = pd.read_csv('close_prices.csv', parse_dates=['date'], index_col='date')

djia = pd.read_csv('djia_index.csv', parse_dates=['date'], index_col='date')

In [ ]:
df

,AXP,BA,CAT,CSCO,CVX,DD,DIS,GE,GS,HD,...,PFE,PG,T,TRV,UNH,UTX,V,VZ,WMT,XOM
date,,,,,,,,,,,,,,,,,,,,,
2013-09-23,76.440002,117.510002,85.029999,24.270000,125.519997,59.409999,64.750000,24.280001,165.250000,75.910004,...,28.799999,79.279999,34.220001,86.379997,71.820000,109.419998,196.240005,47.980000,76.419998,87.750000
2013-09-24,76.070000,119.000000,85.110001,24.139999,124.489998,59.319997,64.320000,24.320000,162.970001,76.040001,...,28.709999,78.620003,34.090000,85.870003,72.320000,110.000000,193.339996,47.270000,75.750000,87.360001
2013-09-25,75.989998,118.510002,84.500000,24.430000,124.070000,59.319997,64.449997,24.230000,162.309998,75.519997,...,28.490000,77.720001,34.049999,85.980003,71.980003,109.260002,191.559998,46.950001,74.650002,87.139999
2013-09-26,76.320000,119.379997,84.199997,23.770000,123.489998,59.509996,65.239998,24.250000,162.289993,76.070000,...,28.520000,78.050003,34.230000,85.830002,72.160004,109.660004,193.559998,47.669998,74.620003,87.070000
2013-09-27,75.889999,118.739998,83.800003,23.330000,122.639999,59.009995,65.190002,24.049999,159.850006,75.959999,...,28.879999,77.209999,33.980000,85.410004,71.989998,109.360001,193.050003,47.000000,74.360001,86.900002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-03-12,81.559998,152.039993,80.190002,28.240000,102.419998,80.400001,107.169998,25.400000,189.949997,116.099998,...,34.000000,82.089996,33.130001,107.830002,114.879997,121.239998,269.579987,48.730000,81.900002,84.220001
2015-03-13,80.599998,151.570007,79.230003,27.940001,101.620003,80.499997,106.440002,25.040001,189.339996,114.820000,...,34.000000,81.830002,32.759998,106.720001,115.250000,118.739998,265.029999,48.840000,81.900002,83.870003
2015-03-16,81.500000,153.669998,79.970001,28.299999,103.129997,77.069994,107.370003,25.450001,191.899994,116.500000,...,34.439999,83.559998,33.060001,108.930000,118.519997,120.070000,269.019989,49.270000,83.290001,84.760002
2015-03-17,81.059998,154.509995,78.449997,28.150000,103.169998,74.680001,106.959999,25.309999,190.570007,115.580002,...,34.169998,82.849998,32.900002,108.750000,117.599998,119.860001,264.500000,48.950001,82.620003,84.080002
2015-03-18,81.860001,155.729996,81.330002,28.150000,106.699997,76.009997,107.970001,25.639999,192.320007,116.080002,...,34.380001,83.750000,33.590000,109.519997,119.959999,120.309998,267.670013,49.540001,82.529999,86.070000

In [ ]:
djia

                    ^DJI
date
2013-09-23  15401.379883
2013-09-24  15334.589844
2013-09-25  15273.259766
2013-09-26  15328.299805
2013-09-27  15258.240234
...                  ...
2015-03-12  17895.220703
2015-03-13  17749.310547
2015-03-16  17977.419922
2015-03-17  17849.080078
2015-03-18  18076.189453

[374 rows x 1 columns]

 2. На загруженных данных обучите преобразование PCA с числом
 компоненты равным 10. Скольких компонент хватит, чтобы объяснить 90% дисперсии?

In [ ]:
from sklearn.decomposition import PCA

# для 10 компонетов
pca = PCA(n_components=10)
pca.fit(df)

# объясняет более 90% дисперсии
import numpy as np
explained_variance = np.cumsum(pca.explained_variance_ratio_)
num_components_90 = np.argmax(explained_variance >= 0.9) + 1
print(num_components_90)

4

In [ ]:
explained_variance

array([0.73897118, 0.84904287, 0.89899376, 0.92774295, 0.94989743,
       0.9692132 , 0.97596173, 0.98210264, 0.98530858, 0.98836469])

 3. Применитепостроенное преобразование к исходным данным и возь
мите значения первой компоненты.

In [ ]:
X_pca = pca.transform(df)
first_component = X_pca[:, 0]

 4. Загрузите информацию об индексе Доу-Джонса из файла djia_prices.csv.
 Чему равна корреляция Пирсона между первой компонентой и индексом Доу-Джонса?

In [ ]:
correlation = np.corrcoef(first_component, djia['^DJI'])[0, 1]
print(round(correlation, 2))

0.91

 5. Какая компания имеет наибольший вес в первой компоненте?

In [ ]:
weights = pca.components_[0]

company_weights = pd.Series(weights, index=df.columns)

most_influential = company_weights.abs().idxmax()
print(most_influential)

V